.TH RDATE 1 "4 Pluviôse an CCXXX" "Wafelack" "Commandes Utilisateur"

.SH NOM
rdate \- date suivant le calendrier républicain
.SH SYNOPSIS
.B rdate 
[-g \fIDATEG\fR]
[-f \fIFORMATG\fR]
[\fIFORMAT\fR]
.SH OPTIONS
  -g \fIDATEG\fR        La date du calendrier grégorien à traduire en fonction de \fIFORMATG\fR.

  -f \fIFORMATG\fR      Le format de traduction pour \fIDATEG\fR.
.br
                  Valeur par défaut : « %a %b %d %I:%M:%S %p %Z %Y ».
.br
                  Voir strptime(3p) pour la liste des directives de format acceptées.
.SH DESCRIPTION
Cet utilitaire affiche la date et l'heure sur la sortie standard, sauf si l'argument \fB-g\fR est fourni.
.br
Si cet argument est fourni, \fBrdate\fR va seulement traduire la date donnée.
.br
Par défaut, la date et l'heure sont affichées selon le format « %a %d %b (%N) %H:%M:%S %y ».

.SH OPÉRANDES
Les opérandes suivantes sont supportées afin de spécifier le format de sortie :
.br
	%a	Nom abrégé du jour de la semaine.

	%b	Nom abrégé du mois.

	%A	Nom complet du jour de la semaine.

	%B	Nom complet du mois.

	%c	Équivalent à « %a %d %b %H:%M:%S %Y »

	%C	Siècle en tant que nombre décimal.

	%d	Jour du mois en tant que nombre décimal [00 ; 30].

	%D	Équivalent à « %m/%d/%y ».

	%F	Équivalent à « %Y-%m-%d ».

	%H	Heure en tant que nombre décimal [00 ; 9].

	%j	Jour de l'année en tant que nombre décimal [001 ; 366].

	%m	Mois en tant que nombre décimal [01 ; 13].

	%M	Minute en tant que nombre décimal [00 ; 99].

	%n	Saut de ligne.

	%q	Trimestre en tant que nombre décimal [1 ; 4].

	%R	L'heure au format « %H:%M ».

	%S	Seconde en tant que nombre décimal [00 ; 99].

	%t	Une tabulation.

	%T	L'heure au format « %H:%M:%S ».

	%u	Jour de la semaine en tant que nombre décimal [1 ; 7].

	%w	Jour de la semaine en tant que nombre décimal [0 ; 6].

	%y	L'année en tant que nombre décimal.

	%Y	L'année en chiffres romains précédée de « An ».

	%N	Le nom de l'animal / plante / outil associé au jour d'hui.

	%%	Le caractère ‘%’.
.SH EXEMPLES
$ rdate "%A %d %B - %H:%M"
.br
Nonidi 29 Frimaire - 6:67
.SH VOIR AUSSI
date(1p)
.SH AUTEUR
Écrit par Wafelack <wafelack@riseup.net>.
.SH DROITS DE COPIE
Copyright \(co 2021-2022 (An 230 de la République) Wafelack
.br
Distribué sous licence GPLv3+ : GNU GPL version 3 ou ultérieure <https://www.gnu.org/licenses/gpl-3.0.fr.html>.
.br
Ceci est un logiciel libre : vous êtes libre de le modifier et de le redistribuer.
Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE ;
sans même une garantie implicite de COMMERCIABILITÉ ou DE CONFORMITÉ À UNE UTILISATION PARTICULIÈRE.
